# Generated by Django 4.2.4 on 2026-03-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CrmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(blank=True, default='idle', max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('processed', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('eta_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255, unique=True)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_number', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='salary_app.company', to_field='company_id')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='salary_app.crmuser')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='salary_app.crmuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expense date')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='salary_app.employee', verbose_name='Employee')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='salary_app.expensetype', verbose_name='Expense type')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('table_data', models.JSONField(blank=True, null=True, verbose_name='Table data')),
                ('token_usage', models.JSONField(blank=True, null=True, verbose_name='Token usage')),
                ('conversation_history', models.JSONField(blank=True, null=True, verbose_name='Conversation history')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_history', to='salary_app.crmuser')),
            ],
            options={
                'verbose_name': 'AI analysis history record',
                'verbose_name_plural': 'AI analysis history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='salary_app__created_a8fe92_idx'), models.Index(fields=['manager', '-created_at'], name='salary_app__manager_203b9f_idx')],
            },
        ),
    ]
