# Generated by Django 5.2.2 on 2025-09-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salary_app", "0002_employee_expensetype_productionexpense"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
