# Generated by Django 5.2.6 on 2025-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0003_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
