"""
Django settings for salary project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located at project root
load_dotenv(BASE_DIR / '.env')

# SECURITY: Store your Bitrix24 webhook URL base in an environment variable
# e.g. 'https://your-domain.bitrix24.ru/rest/1/yoursecretkey'
BITRIX_WEBHOOK_BASE = os.getenv('BITRIX_WEBHOOK_BASE')

if not BITRIX_WEBHOOK_BASE:
    raise ImproperlyConfigured("BITRIX_WEBHOOK_BASE is not set. Please configure the environment variable.")

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Load from environment.
SECRET_KEY = os.getenv('SECRET_KEY', "dev-insecure-secret-key")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')
if not DEBUG and (not SECRET_KEY or SECRET_KEY == "dev-insecure-secret-key"):
    raise ImproperlyConfigured("SECRET_KEY must be set in production.")

ALLOWED_HOSTS = [
    # Add your production domain here
    '.ngrok-free.app', 'localhost', '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]

# Application definition

INSTALLED_APPS = [
    'salary_app',
    'widget_tweaks',
    'compressor',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'salary.urls'

CSRF_USE_SESSIONS = True
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'salary_app.context_processors.global_user_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'salary.wsgi.application'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_AGE = 1800
SESSION_SAVE_EVERY_REQUEST = True
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # SECURITY WARNING: Load database credentials from environment variables in production
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'my_new_database'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'newpassword'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {"min_length": 8}, 
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True
LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = not DEBUG
COMPRESS_OFFLINE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  # куда перенаправлять после успешного входа
LOGOUT_REDIRECT_URL = '/login/'

# GPT-OSS-120B Model Settings
GPT_MODEL_PATH = os.getenv('GPT_MODEL_PATH', '')
GPT_MODEL_TYPE = os.getenv('GPT_MODEL_TYPE', 'llama-cpp')  # Options: 'llama-cpp', 'transformers', 'vllm', 'llama-server'
GPT_N_CTX = int(os.getenv('GPT_N_CTX', '4096'))  # Context window size
GPT_N_THREADS = int(os.getenv('GPT_N_THREADS', '4'))  # Number of threads
GPT_N_GPU_LAYERS = int(os.getenv('GPT_N_GPU_LAYERS', '0'))  # Number of GPU layers (0 = CPU only)
# llama-server API settings
LLAMA_SERVER_API_BASE = os.getenv('LLAMA_SERVER_API_BASE', 'http://localhost:8080')  # llama-server API base URL
# llama-server auto-start settings
LLAMA_SERVER_PATH = os.getenv('LLAMA_SERVER_PATH', '')  # Path to llama-server.exe
LLAMA_AUTO_START = os.getenv('LLAMA_AUTO_START', 'True').lower() in ('1', 'true', 'yes', 'on')  # Auto-start llama-server
# llama-server parameters (from user's command)
LLAMA_FLASH_ATTENTION = os.getenv('LLAMA_FLASH_ATTENTION', '1')
LLAMA_NCMOE = os.getenv('LLAMA_NCMOE', '25')
LLAMA_NGL = os.getenv('LLAMA_NGL', '40')
LLAMA_UB = os.getenv('LLAMA_UB', '2048')
LLAMA_BATCH = os.getenv('LLAMA_BATCH', '2048')
LLAMA_CONTEXT = os.getenv('LLAMA_CONTEXT', '32768')
LLAMA_JINJA = os.getenv('LLAMA_JINJA', 'True').lower() in ('1', 'true', 'yes', 'on')